### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by nielserik**

### CODE REVIEW

**Comment by nielserik** [comment]
Agreed with David to put the documentation written so far into ui-testing's own README, with the intention of linking to it from elsewhere. 

David will take a look and we'll take it from there.

**Review by dcrossleyau — COMMENTED** [review]
I did review. It needed only minor tidy.

Not sure about the level of some of the headings.

Wondering if a Table of Contents would help.

Anyway, later, this is good for a first round.

**Comment by nielserik** [comment]
Great @dcrossleyau. 

Agreed that there's something about the structure in sections and paragraphs that might be straightened, couldn't put my finger on it.  Also thought of a ToC, as this now got somewhat longer and covers more aspects. 

Anyways, maybe @cledvina will check if things make sense before I merge the pull request. 

Thank you, David!

**Comment by cledvina** [comment]
Very nice, NE and David.

**Pull request merged**
