### PR TITLE
UITEST-27 - Write a test that exercises location setup

### PR DESCRIPTION
**Pull request by khemchandra**
The test should do the   following:   
1) click settings   
2) click organization   
3) create an institution   
4) create a campus attached to the above institution   
5) create a library at the above campus   
6) add a location to the above library   
7) clean up new settings

### CODE REVIEW

**Comment by zburke** [comment]
Aw, man, I didn't realize we had these tests under ui-testing and just merged some [similar code in ui-organizations](/folio-org/ui-organization/pull/84). Unfortunately, a bunch of the underlying selectors have changed, breaking some of the tests you wrote. 

Since you are already familiar with the ui-organization module and the location management code, would you be willing to contribute some tests that would exercise the validation, e.g. making sure warnings are present and submission is disabled if required fields are missing, and likewise for fields that need to have unique values (name, code)? 

I'm sorry, again, that I missed this work!

**Comment by khemchandra** [comment]
Hello,

Sure I can work on the additional tests. Will they be added to the ui-testing repo?

Regards,
Khem

**Comment by zburke** [comment]
Let's put them in [ui-organization](/folio-org/ui-organization) instead. We have moved most integration tests out of ui-testing and into their respective repositories. Current locations tests are in `ui-organization/test/ui-testing/locations.js`.

**Comment by khemchandra** [comment]
Ok can do. The tests to add are 
-	making sure warnings are present, 
-	submission is disabled if required fields are missing, 
-	and likewise for fields that need to have unique values (name, code)

**Pull request merged**
