### PR TITLE
Adjust tests for Scan ID setting. Fixes UITEST-19

### PR DESCRIPTION
**Pull request by mkuklis**

### CODE REVIEW

**Comment by mkuklis** [comment]
@nielserik and @cledvina I moved `Scan Id` settings page under `ui-circulation` and had to adjust couple tests. The changes should also address failing tests due to the refactoring which happened on the `Scan Id` page.

**Comment by MikeTaylor** [comment]
Doesn't it seem wrong that ui-testing needs to know about how ui-checkout/ui-circulation are laid out?  Shouldn't ui-testing itself be completely neutral mechanism, with _all_ the actual tests being in the modules themselves?

**Comment by mkuklis** [comment]
@MikeTaylor that's a good question. It does make sense to me to keep them in the individual modules.

**Comment by MikeTaylor** [comment]
@cledvina Can you comment on this?

**Pull request merged**
